### ISSUE TITLE
Japanese text seems mismatched with audio

### ISSUE THREAD

**Issue by meridion** [mozilla/common-voice#2553] opened 2020-02-03 00:24 UTC
I am opening this issue because I am encountering an immense amount of completely incorrect audio samples in the Japanese version of common voice.

Some spoken sentences start out with the same words but end completely differently. Most spoken sentences have nothing to do with the text on the card.

However, all these sentences do sound like they came from an existing card, just not the one shown.

Since all the sentences I heard today however were spoken by the same speaker I have to conclude that either, somehow this speaker has incorrectly submitted many sentences, which I find unlikely considering the automated process by which sentences are obtained. Or somehow something is going wrong in the reproduction of Japanese to the person doing the checking. (as an alternative the mistake would happen during the storage of audio data)

If somebody could verify either I would be helped. Otherwise I will be incorrectly invalidating over 95% of the sentences I encountered. Which is a shame since the audio samples do seem to make sense, just not for the cards shown.

I verified I had this issue in both Firefox and Chromium. Furthermore English and Dutch seem to be working fine.

**Comment by phirework** [comment] 2020-02-10 14:38
@meridion Thanks for reporting this! Is this something you just started noticing or has this been happening the entire time you've been using Common Voice? Also, next time you notice this happening, could you note down the sentence in the card and what you think the sentence should've been and let me know? I'd love to be able to narrow this down further.

**Comment by meridion** [comment] 2020-02-11 12:57
Alright, here goes:
card text: 不平を言っても無駄だ。
spoken text: 父は私たちの結婚を反対した。

card text: 副官は戦術の変更を彼に提案した。
spoken text: パーティーの料理がおいしくありませんでした。

card text: 評論家たちは経済規制の強化を激しく非難しています。
spoken text: 彼女は父親の死から立ち直った。

card text: 遺留品といっては、糸一本も落ちていなかった。
spoken text: 父は友達と仲良くやっている。

It has been quite a while since I last used common voice, but I don't remember Japanese having this problem at the time.

Since Japanese allows for different choices in writing down a spoken sentence, the spoken text I have produced might differ slightly in kana/kanji choice from the ground truth.

**Comment by phirework** [comment] 2020-02-11 15:48
Awesome, thank you so much for this!

**Comment by rileyjshaw** [comment] 2020-07-24 17:49
Hi @meridion, I've made a few fixes to the way we deliver and match sentences since you logged this issue. Are you able to check if the problem is still occurring?

Thanks so much for reporting this!

**Comment by meridion** [comment] 2020-07-25 13:38
That's great to hear.

Unfortunately it currently says, there is simply not enough data for listening, so I'll have to wait until more speakers of Japanese upload.

**Comment by meridion** [comment] 2020-08-04 18:22
Okay, I've done a few sentences, and they seem fine now.

The only problem I had this time was, some recordings were completely silent, which might be due to something else entirely.

So all in all, sentence matching seems fine now.

**Comment by rileyjshaw** [comment] 2020-08-05 15:06
@meridion that's great, thanks for getting back to us. We're tracking [silent clips in a separate issue](https://github.com/mozilla/common-voice/issues/2824), so I'm going to close this one for now. Thanks again for reporting!

**Closed by rileyjshaw** 2020-08-05 15:06 UTC
Labels: Status: info-needed, Type: Bug
