### ISSUE TITLE
English shown last

### ISSUE THREAD

**Issue by davidak** [mozilla/common-voice#2834] opened 2020-07-17 19:29 UTC
**Describe the bug**
English has the most recordings, but is shown last on the german site.

**To Reproduce**
1. Go to https://voice.mozilla.org/de/languages
2. Click on 'Mehr anzeigen'
3. Scroll down to 'Englisch'

**Expected behavior**
first in list

**Screenshots**
![Screenshot from 2020-07-17 21-17-08](https://user-images.githubusercontent.com/91113/87823758-48b7fb80-c874-11ea-85a1-f5bb76c87091.png)

on the english site it's correct
![Screenshot from 2020-07-17 21-23-23](https://user-images.githubusercontent.com/91113/87823780-579eae00-c874-11ea-85e2-3dbea2dab834.png)

**Desktop or Mobile (please complete the following information):**
 - OS: NixOS 20.03.1950.48723f48ab9 (Markhor)
 - Browser: Chromium 81.0.4044.138

**Comment by phirework** [comment] 2020-08-05 21:04
Thanks for reporting this! The intended behaviour is that the language that's currently selected should be first, and then everything else is sorted by # of hours validated, so that's been fixed now. https://commonvoice.mozilla.org/de/languages

**Closed by phirework** 2020-08-05 21:04 UTC
